#!/bin/bash

for file_name in "$@"; do
    if [[ (-e "$file_name") ]]; then
        read -e -i "$(basename "$file_name")" new_file_name
        dir_name=`dirname "$file_name"`
        mv "$file_name" "${dir_name}/${new_file_name}"
    fi
done
