#!/bin/bash

interval="$1"
shift 1

dir_name="/tmp/.watchthis"
if [[ !(-d "$dir_name") ]]; then
    mkdir "$dir_name"
fi

prev="$dir_name/previous"
cur="$dir_name/current"
"$@" > "$cur"
echo -n "" > "$prev"
cat "$cur"
diff -u "$cur" "$prev"

while true; do
    sleep "$interval"
    cat "$cur" > "$prev"
    "$@" > "$cur"
    cat "$cur"
    diff -u "$cur" "$prev"
done
